name: CI
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    permissions:
      packages: write
    strategy:
      matrix:
        images:
          - tag: eln
            repo: eln.repo
            excludes: dnf-bootc dnf-yum rhc
          - tag: a9
            repo: almalinux9.repo
            excludes: rhc
          - tag: a10s
            repo: almalinux10s.repo
            excludes: dnf-bootc dnf-yum rhc
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login to container registry
        run: echo ${{secrets.GITHUB_TOKEN}} | podman login -u ${{github.actor}} --password-stdin ghcr.io
      - name: Build image
        run: podman build --security-opt=label=disable --cap-add=all --device /dev/fuse --build-arg repo=${{matrix.images.repo}} --build-arg excludes="${{matrix.images.excludes}}" -t ghcr.io/charles25565/unified-bootc-images:${{matrix.images.tag}} .
      - name: Push image
        if: github.event_name != 'pull_request'
        run: podman push ghcr.io/charles25565/unified-bootc-images:${{matrix.images.tag}}
